clone:
  git:
    image: plugins/git # Drone 自維護的 git image
    depath: 50 # default 也是 50，只抓 commit 前 50 的

pipeline:
  node:
    image: node:8.3.0
    commands:
      - yarn install
      - yarn test