workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  fail:
    image: node:8.3.0
    commands:
      - exit 1

  master:
    image: node:8.3.0
    commands:
      - echo master
    when:
      branch: master

  develop:
    image: node:8.3.0
    commands:
      - echo develop
    when:
      branch: develop

  push:
    image: node:8.3.0
    commands:
      - echo push
    when:
      event: [push]

  pull_request:
    image: node:8.3.0
    commands:
      - echo pull_request
    when:
      event: [pull_request]

  tags:
    image: node:8.3.0
    commands:
      - echo tags
    when:
      event: [tag]

  success:
    image: node:8.3.0
    commands:
      - echo success

  notify:
    image: node:8.3.0
    commands:
      - echo notify
    when:
      status: [failure]