workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  frontend:
    image: node:8.3.0
    secrets: [ api_token ]
    commands:
      - yarn install
      - ./node_modules/.bin/mocha
      - node env.js